### ISSUE TITLE
Can't get it to work with ZF3

### ISSUE THREAD

**Issue by metalinspired** [juriansluiman/Soflomo-Purifier#4]
For some reason PurifierFilterFactory is not being called.
Instead, as can be seen from error, ZF tries to invoke it with InvokableFactory.

`
Argument 1 passed to Soflomo\Purifier\PurifierFilter::__construct() must be an instance of HTMLPurifier, none given, called in /project/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php on line 30`

It is properly called using FQCN

```
public function getInputFilterSpecification()
    {
        return [
            'content' => [
                'filters' => [
                    ['name' => PurifierFilter::class]
                ]
            ],
        ];
    }
```

**Comment by stefanotorresi** [comment]
does using the alias `htmlpurifier` yield the same result?

**Comment by metalinspired** [comment]
No.
`A plugin by the name "htmlpurifier" was not found in the plugin manager Zend\Filter\FilterPluginManager`

**Comment by stefanotorresi** [comment]
did you add the `Soflomo\Purifier` to the list of your application modules?

**Comment by metalinspired** [comment]
Yes.

**Comment by stefanotorresi** [comment]
I can't seem to reproduce your problem, it looks like your application is not loading the module at all.
Are you able to pull the `HTMLPurifier` service from the ServiceManager in your application?

**Comment by metalinspired** [comment]
Yes I am.
I tried `$container->get('HTMLPurifier')` from one of my own factories and it yields a `HTMLPurifier` instance but the problem is that `PurifierFilterFactory` is not getting called when I try to add `PurifierFilter` to a filter chain.
`Soflomo\Purifier\Module.php` is getting loaded and that's why I can't see whats wrong.

**Comment by metalinspired** [comment]
Found the problem.
It was on my side.
I was missing `Zend\InputFilter` in list of my modules.
