### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by andrconstruction** [juriansluiman/Soflomo-Purifier#6]
Can you advise how to integrate this module into ZF3?

**Comment by exptom** [comment]
@andrconstruction The 2.0.0-beta tag works on ZF3

**Comment by andrconstruction** [comment]
And hello again. Installed last version, but have an other error 
A plugin by the name "htmlpurifier" was not found in the plugin manager Zend\Filter\FilterPluginManager
Advise please what do I wrong?

Form create throug init()

**Comment by exptom** [comment]
@andrconstruction can you link to your code?

**Comment by andrconstruction** [comment]
Which part?

**Comment by exptom** [comment]
Anything related to this plugin settings and usage in a form.

**Comment by andrconstruction** [comment]
a form : https://pastebin.com/PpQuVnP2
calling the form : https://pastebin.com/LH0mycPT
config https://pastebin.com/56im3D4S
modules.config.php ^
   'Soflomo\Purifier',
        'Application',
        'Support',

**Comment by exptom** [comment]
Have you enabled the module in the main module config?

**Comment by andrconstruction** [comment]
Of course https://pastebin.com/KFwzGQmt

**Comment by exptom** [comment]
Probably not the issue but you've got the module listed twice.

**Comment by andrconstruction** [comment]
One thing what I suspect. It is a path. I download the zip and unpack it to /vendor/soflomo/purifier

**Comment by exptom** [comment]
I would advise that you use composer for all application dependencies.

**Comment by andrconstruction** [comment]
Removed second 'Soflomo\Purifier', not helped

**Comment by andrconstruction** [comment]
my composer
https://pastebin.com/ysvxa6DU

**Comment by exptom** [comment]
You need to be using the 2.0.0-beta version, not 1.0 with ZF3.

`"soflomo/purifier": "2.0.0-beta"`

**Comment by andrconstruction** [comment]
Maybe  should I  explicity declare the soflomo module within a psr4 namespaece with my modules?

**Comment by andrconstruction** [comment]
How to install from your repository ^
c require "soflomo/purifier": "2.0.0-beta" show [InvalidArgumentException]                  
  Could not find package "soflomo/purifier".  
                                            
  Did you mean this?                          
      soflomo/purifier                


But your repository declared 

  "repositories": [
    {
      "type" : "git",
      "url"  : "https://github.com/juriansluiman/Soflomo-Purifier.git",
      "options": {
        "ssl": {
          "verify_peer": "false"
        }
      }
    }
  ],

**Comment by exptom** [comment]
You don't need the "repositories" section at all, you can remove it.

Then in the "require" just add the line:
`"soflomo/purifier": "2.0.0-beta"`

Like this: https://gist.github.com/exptom/a9ab482a186db8ff0135e3a7d8f22fc3

**Comment by andrconstruction** [comment]
unfortunatly nothing changed the error still here
composers : https://pastebin.com/91vDH8v5

**Comment by andrconstruction** [comment]
anyway big thanks for your spent time, I Will dig next

**Comment by andrconstruction** [comment]
My problem it is a not working  factory. As I suspect a fiilter factory should implements FilterFactoryInterface, but now it implements a FactoryInterface. Advice please, may this is a my problem?

**Comment by andrconstruction** [comment]
Error was a simple. Was not registered the Zend/Filter module within a config. After added , the problem is gone.
